apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: svc
  labels: { app: frontend }
spec:
  selector: { app: frontend }
  ports:
    - { name: http, port: 80, targetPort: 80 }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: svc
spec:
  replicas: 1
  selector:
    matchLabels: { app: frontend }
  template:
    metadata:
      labels: { app: frontend }
    spec:
      containers:
        - name: nginx
          image: nginxdemos/hello:plain-text
          ports: [ { containerPort: 80 } ]
          readinessProbe:
            httpGet: { path: "/", port: 80 }
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: "/", port: 80 }
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: svc
  annotations:
    cert-manager.io/issuer: ebank-ca
spec:
  ingressClassName: nginx
  tls:
    - hosts: [ "ebank.local" ]
      secretName: ebank-tls
  rules:
    - host: ebank.local
      http:
        paths:
          - path: /app
            pathType: Prefix
            backend:
              service:
                name: frontend
                port: { number: 80 }
