apiVersion: v1
kind: Namespace
metadata:
  name: dmz
  labels: { zone: dmz }
---
apiVersion: v1
kind: Namespace
metadata:
  name: svc
  labels: { zone: svc }
---
apiVersion: v1
kind: Namespace
metadata:
  name: data
  labels: { zone: data }
---
apiVersion: v1
kind: Namespace
metadata:
  name: security
  labels: { zone: security }
