apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
  namespace: ebanking-backend
type: Opaque
data:
  # Base64 encoded VAPID keys (replace with actual keys)
  vapid-public-key: Qk1GdDBLLVlOc1h4ZmZCTVZKRE1MMVRYUWhhOVc2VjdmT1h6VXdNTjJvdz0=
  vapid-private-key: WVhwemRHaHNJR1poWkhRZ2FHVnlaUzVuWlc1bGNtRjBaU0JoSUc1bGR5QnJaWGt1
