apiVersion: v1
kind: Service
metadata:
  name: mssql
  namespace: data
  labels: { app: mssql }
spec:
  ports:
    - port: 1433
      targetPort: 1433
      name: tds
  clusterIP: None
  selector: { app: mssql }
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql
  namespace: data
spec:
  serviceName: mssql
  replicas: 1
  selector:
    matchLabels: { app: mssql }
  template:
    metadata: { labels: { app: mssql } }
    spec:
      securityContext: { fsGroup: 10001 }
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports: [ { containerPort: 1433, name: tds } ]
          env:
            - { name: ACCEPT_EULA, value: "Y" }
            - name: SA_PASSWORD
              valueFrom: { secretKeyRef: { name: mssql-secret, key: SA_PASSWORD } }
          volumeMounts:
            - { name: data, mountPath: /var/opt/mssql }
  volumeClaimTemplates:
    - metadata: { name: data }
      spec:
        accessModes: ["ReadWriteOnce"]
        resources: { requests: { storage: 10Gi } }
