apiVersion: v1
kind: Secret
metadata:
  name: mssql-secret
  namespace: ebanking-backend
type: Opaque
stringData:
  SA_PASSWORD: "Str0ng!Passw0rd1!"
  
  # Connection strings for microservices
  account-connection-string: "Server=mssql.data.svc.cluster.local,1433;Database=EBanking_Account;User Id=sa;Password=Str0ng!Passw0rd1!;TrustServerCertificate=true;"
  transfer-connection-string: "Server=mssql.data.svc.cluster.local,1433;Database=EBanking_Transfer;User Id=sa;Password=Str0ng!Passw0rd1!;TrustServerCertificate=true;"
  payment-connection-string: "Server=mssql.data.svc.cluster.local,1433;Database=EBanking_Payment;User Id=sa;Password=Str0ng!Passw0rd1!;TrustServerCertificate=true;"
  notification-connection-string: "Server=mssql.data.svc.cluster.local,1433;Database=EBanking_Notification;User Id=sa;Password=Str0ng!Passw0rd1!;TrustServerCertificate=true;"
  audit-connection-string: "Server=mssql.data.svc.cluster.local,1433;Database=EBanking_Audit;User Id=sa;Password=Str0ng!Passw0rd1!;TrustServerCertificate=true;"
---
apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
  namespace: ebanking-backend
type: Opaque
stringData:
  # VAPID keys for Web Push notifications 
  # Generate these with: npx web-push generate-vapid-keys
  vapid-public-key: "BMHr5tEt6tH0OjnRUjeSvMX2Kf80HqIjZPBnLuixqYbdWlfIs0faCVcQmMuv_NgA"
  vapid-private-key: "pars8ry1wWbOdtWVUoANbnB2S18CRQsJdMhzfpjyBpI"
  vapid-subject: "mailto:admin@ebank.local"
