apiVersion: v1
kind: Secret
metadata:
  name: mssql-secret
  namespace: ebanking-backend
type: Opaque
stringData:
  SA_PASSWORD: "Str0ng!Passw0rd1!"
  # All services now use the same database
  default-connection-string: "Server=mssql.data.svc.cluster.local,1433;Database=EBanking;User Id=sa;Password=Str0ng!Passw0rd1!;TrustServerCertificate=true;"
  
  # Keep individual connection strings for backward compatibility during migration
  account-connection-string: "Server=mssql.data.svc.cluster.local,1433;Database=EBanking;User Id=sa;Password=Str0ng!Passw0rd1!;TrustServerCertificate=true;"
  audit-connection-string: "Server=mssql.data.svc.cluster.local,1433;Database=EBanking;User Id=sa;Password=Str0ng!Passw0rd1!;TrustServerCertificate=true;"
  notification-connection-string: "Server=mssql.data.svc.cluster.local,1433;Database=EBanking;User Id=sa;Password=Str0ng!Passw0rd1!;TrustServerCertificate=true;"
  payment-connection-string: "Server=mssql.data.svc.cluster.local,1433;Database=EBanking;User Id=sa;Password=Str0ng!Passw0rd1!;TrustServerCertificate=true;"
  transfer-connection-string: "Server=mssql.data.svc.cluster.local,1433;Database=EBanking;User Id=sa;Password=Str0ng!Passw0rd1!;TrustServerCertificate=true;"