apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: svc
  labels: { app: api-gateway }
spec:
  selector: { app: api-gateway }
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: svc
spec:
  replicas: 1
  selector:
    matchLabels: { app: api-gateway }
  template:
    metadata:
      labels: { app: api-gateway }
    spec:
      containers:
        - name: gateway
          image: ebanking/api-gateway:latest
          imagePullPolicy: Never
          ports: [ { containerPort: 8080 } ]
          env:
            - name: ASPNETCORE_URLS
              value: "http://0.0.0.0:8080"
          volumeMounts:
            - name: cfg
              mountPath: /app/appsettings.json
              subPath: appsettings.json
            - name: ocelot
              mountPath: /app/ocelot.json
              subPath: ocelot.json
      volumes:
        - name: cfg
          configMap:
            name: gateway-ocelot-config
            items: [ { key: appsettings.json, path: appsettings.json } ]
        - name: ocelot
          configMap:
            name: gateway-ocelot-config
            items: [ { key: ocelot.json, path: ocelot.json } ]
