apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: svc
  labels: { app: api-gateway }
spec:
  selector: { app: api-gateway }
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: svc
spec:
  selector:
    matchLabels: { app: api-gateway }
  replicas: 1
  template:
    metadata:
      labels: { app: api-gateway }
    spec:
      containers:
        - name: gw
          image: ealen/echo-server:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet: { path: "/", port: 80 }
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: "/", port: 80 }
            initialDelaySeconds: 5
            periodSeconds: 10
